name: xeus-lua
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus-zmq>=1.3.0, <2.0
  - nlohmann_json=3.11.2
  - cppzmq
  - xtl>=0.7
  - lua>=5.2.0
  - openlibm # [linux]
<<<<<<< HEAD
  - xwidgets <0.28
  - xcanvas>=0.4.1
=======
  - xwidgets <0.29
  - xcanvas>=0.4.2
>>>>>>> upstream/main
  # to try it out
  - jupyterlab
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test
