name: xeus-lua
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus-zmq>=1.0, <2.0
  - nlohmann_json
  - cppzmq
  - xtl>=0.7, <0.8
  - lua>=5.2.0
  - openlibm # [linux]
  - xwidgets>=0.27.3
  - xcanvas>=0.4.1
  # to try it out
  - jupyterlab
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test
