name: xeus-lua
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  # Host dependencies
  - xeus
  - nlohmann_json
  - cppzmq
  - xtl
  # Test dependencies
  - pytest
  - jupyter_kernel_test
  - nbval
