name: xeus-lua
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus>=5.0,<=6
  - xeus-zmq
  - nlohmann_json=3.11.2
  - cppzmq
  - lua>=5.2.0
  - openlibm # [linux]
  - xwidgets <0.29
  - xcanvas>=0.4.2
  # to try it out
  - jupyterlab
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test
