name: xeus-lua-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - lua
  - nlohmann_json
  - xeus-lite <2.0
  - xeus >=3.2.0,<4.0
  - xtl >=0.7,<0.8
  - xcanvas >=0.4,<5.0
  - xwidgets >=0.27.3,<1.0

  - xwidgets >=0.27.3,<1.0